spring:
  datasource:
    url: jdbc:mysql://47.100.222.96:3306/exercise?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: tan
    password: Tanqw5201314.
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid